# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\LAVORO\PRODAR\CLAUDIA\CARRELLI\carrelli elettrici\PYTHON\CARRELLI_SMAO_SMIOO\widgets\measurement_card\measurement_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MeasurementCard(object):
    def setupUi(self, MeasurementCard):
        MeasurementCard.setObjectName("MeasurementCard")
        MeasurementCard.resize(180, 180)
        MeasurementCard.setMinimumSize(QtCore.QSize(180, 160))
        MeasurementCard.setMaximumSize(QtCore.QSize(180, 300))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MeasurementCard.sizePolicy().hasHeightForWidth())
        MeasurementCard.setSizePolicy(sizePolicy)
        MeasurementCard.setStyleSheet("QFrame#MeasurementCard {\n"
"    background-color: #4CAF50;\n"
"    border: 2px solid #555;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QFrame#MeasurementCard:hover {\n"
"    border: 3px solid #000;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        MeasurementCard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        MeasurementCard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(MeasurementCard)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setSpacing(5)
        self.headerLayout.setObjectName("headerLayout")
        self.labelName = QtWidgets.QLabel(MeasurementCard)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.labelName.setFont(font)
        self.labelName.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelName.setWordWrap(True)
        self.labelName.setObjectName("labelName")
        self.headerLayout.addWidget(self.labelName)
        self.btnToggleEnabled = QtWidgets.QPushButton(MeasurementCard)
        self.btnToggleEnabled.setMinimumSize(QtCore.QSize(24, 24))
        self.btnToggleEnabled.setMaximumSize(QtCore.QSize(24, 24))
        self.btnToggleEnabled.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255,255,255,0.3);\n"
"    border: 1px solid white;\n"
"    border-radius: 12px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255,255,255,0.5);\n"
"}")
        self.btnToggleEnabled.setObjectName("btnToggleEnabled")
        self.headerLayout.addWidget(self.btnToggleEnabled)
        self.verticalLayout.addLayout(self.headerLayout)
        self.labelFormula = QtWidgets.QLabel(MeasurementCard)
        self.labelFormula.setMinimumSize(QtCore.QSize(0, 35))
        self.labelFormula.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(8)
        font.setItalic(True)
        self.labelFormula.setFont(font)
        self.labelFormula.setStyleSheet("background-color: rgba(0, 0, 0, 0.15);\n"
"border-radius: 3px;\n"
"padding: 3px;\n"
"color: rgba(255, 255, 255, 200);")
        self.labelFormula.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFormula.setWordWrap(True)
        self.labelFormula.setObjectName("labelFormula")
        self.verticalLayout.addWidget(self.labelFormula)
        self.widgetSensors = QtWidgets.QWidget(MeasurementCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widgetSensors.sizePolicy().hasHeightForWidth())
        self.widgetSensors.setSizePolicy(sizePolicy)
        self.widgetSensors.setMinimumSize(QtCore.QSize(0, 40))
        self.widgetSensors.setStyleSheet("background-color: rgba(0, 0, 0, 0.1);\n"
"border-radius: 3px;")
        self.widgetSensors.setObjectName("widgetSensors")
        self.verticalLayout.addWidget(self.widgetSensors)
        self.labelValue = QtWidgets.QLabel(MeasurementCard)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(True)
        self.labelValue.setFont(font)
        self.labelValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelValue.setObjectName("labelValue")
        self.verticalLayout.addWidget(self.labelValue)

        self.retranslateUi(MeasurementCard)
        QtCore.QMetaObject.connectSlotsByName(MeasurementCard)

    def retranslateUi(self, MeasurementCard):
        _translate = QtCore.QCoreApplication.translate
        self.labelName.setText(_translate("MeasurementCard", "Misura 1"))
        self.btnToggleEnabled.setText(_translate("MeasurementCard", "✓"))
        self.labelFormula.setText(_translate("MeasurementCard", "Doppio click per formula"))
        self.labelValue.setText(_translate("MeasurementCard", "---"))
