# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\LAVORO\PRODAR\CLAUDIA\CARRELLI\carrelli elettrici\PYTHON\CARRELLI_SMAO_SMIOO\widgets\measurements_page\measurements_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MeasurementsPage(object):
    def setupUi(self, MeasurementsPage):
        MeasurementsPage.setObjectName("MeasurementsPage")
        MeasurementsPage.resize(1000, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MeasurementsPage)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameSensors = QtWidgets.QFrame(MeasurementsPage)
        self.frameSensors.setMinimumSize(QtCore.QSize(200, 0))
        self.frameSensors.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frameSensors.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSensors.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSensors.setObjectName("frameSensors")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameSensors)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelSensorsHeader = QtWidgets.QLabel(self.frameSensors)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.labelSensorsHeader.setFont(font)
        self.labelSensorsHeader.setStyleSheet("padding: 5px; background-color: #34495E; color: white; border-radius: 3px;")
        self.labelSensorsHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSensorsHeader.setObjectName("labelSensorsHeader")
        self.verticalLayout.addWidget(self.labelSensorsHeader)
        self.listSensors = QtWidgets.QListWidget(self.frameSensors)
        self.listSensors.setStyleSheet("QListWidget {\n"
"    background-color: #ECF0F1;\n"
"    border: 1px solid #BDC3C7;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 12px;\n"
"    border-radius: 5px;\n"
"    margin: 3px;\n"
"    font-weight: bold;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: #3498DB;\n"
"    color: white;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #2980B9;\n"
"    color: white;\n"
"}")
        self.listSensors.setObjectName("listSensors")
        self.verticalLayout.addWidget(self.listSensors)
        self.horizontalLayout.addWidget(self.frameSensors)
        self.frameActions = QtWidgets.QFrame(MeasurementsPage)
        self.frameActions.setMinimumSize(QtCore.QSize(120, 0))
        self.frameActions.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frameActions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameActions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameActions.setObjectName("frameActions")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameActions)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnNew = QtWidgets.QPushButton(self.frameActions)
        self.btnNew.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.btnNew.setFont(font)
        self.btnNew.setStyleSheet("QPushButton {\n"
"    background-color: #27AE60;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2ECC71;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #229954;\n"
"}")
        self.btnNew.setObjectName("btnNew")
        self.verticalLayout_2.addWidget(self.btnNew)
        self.btnEdit = QtWidgets.QPushButton(self.frameActions)
        self.btnEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEdit.setFont(font)
        self.btnEdit.setStyleSheet("QPushButton {\n"
"    background-color: #3498DB;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5DADE2;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #BDC3C7;\n"
"    color: #7F8C8D;\n"
"}")
        self.btnEdit.setObjectName("btnEdit")
        self.verticalLayout_2.addWidget(self.btnEdit)
        self.btnDelete = QtWidgets.QPushButton(self.frameActions)
        self.btnDelete.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDelete.setFont(font)
        self.btnDelete.setStyleSheet("QPushButton {\n"
"    background-color: #E74C3C;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EC7063;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #BDC3C7;\n"
"    color: #7F8C8D;\n"
"}")
        self.btnDelete.setObjectName("btnDelete")
        self.verticalLayout_2.addWidget(self.btnDelete)
        self.btnDuplicate = QtWidgets.QPushButton(self.frameActions)
        self.btnDuplicate.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDuplicate.setFont(font)
        self.btnDuplicate.setStyleSheet("QPushButton {\n"
"    background-color: #9B59B6;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #BB8FCE;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #BDC3C7;\n"
"    color: #7F8C8D;\n"
"}")
        self.btnDuplicate.setObjectName("btnDuplicate")
        self.verticalLayout_2.addWidget(self.btnDuplicate)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frameActions)
        self.scrollAreaMeasurements = QtWidgets.QScrollArea(MeasurementsPage)
        self.scrollAreaMeasurements.setWidgetResizable(True)
        self.scrollAreaMeasurements.setStyleSheet("QScrollArea {\n"
"    border: none;\n"
"    background-color: #ECF0F1;\n"
"}")
        self.scrollAreaMeasurements.setObjectName("scrollAreaMeasurements")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 638, 578))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelMeasurementsHeader = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.labelMeasurementsHeader.setFont(font)
        self.labelMeasurementsHeader.setStyleSheet("padding: 5px; background-color: #34495E; color: white; border-radius: 3px;")
        self.labelMeasurementsHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMeasurementsHeader.setObjectName("labelMeasurementsHeader")
        self.verticalLayout_3.addWidget(self.labelMeasurementsHeader)
        self.widgetMeasurementsContainer = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widgetMeasurementsContainer.setStyleSheet("background: transparent;")
        self.widgetMeasurementsContainer.setObjectName("widgetMeasurementsContainer")
        self.gridLayoutMeasurements = QtWidgets.QGridLayout(self.widgetMeasurementsContainer)
        self.gridLayoutMeasurements.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutMeasurements.setSpacing(10)
        self.gridLayoutMeasurements.setObjectName("gridLayoutMeasurements")
        self.verticalLayout_3.addWidget(self.widgetMeasurementsContainer)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.scrollAreaMeasurements.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollAreaMeasurements)

        self.retranslateUi(MeasurementsPage)
        QtCore.QMetaObject.connectSlotsByName(MeasurementsPage)

    def retranslateUi(self, MeasurementsPage):
        _translate = QtCore.QCoreApplication.translate
        MeasurementsPage.setWindowTitle(_translate("MeasurementsPage", "Gestione Misure"))
        self.labelSensorsHeader.setText(_translate("MeasurementsPage", "📡 SENSORI"))
        self.btnNew.setText(_translate("MeasurementsPage", "➕ Nuova"))
        self.btnEdit.setText(_translate("MeasurementsPage", "✏️ Modifica"))
        self.btnDelete.setText(_translate("MeasurementsPage", "🗑️ Cancella"))
        self.btnDuplicate.setText(_translate("MeasurementsPage", "📋 Duplica"))
        self.labelMeasurementsHeader.setText(_translate("MeasurementsPage", "📏 MISURE"))
