# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\LAVORO\PRODAR\CLAUDIA\CARRELLI\carrelli elettrici\PYTHON\CARRELLI_SMAO_SMIOO\widgets\io_page\io_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IOPage(object):
    def setupUi(self, IOPage):
        IOPage.setObjectName("IOPage")
        IOPage.resize(900, 650)
        self.gridLayout = QtWidgets.QGridLayout(IOPage)
        self.gridLayout.setObjectName("gridLayout")
        self.labelGestioneIO = QtWidgets.QLabel(IOPage)
        self.labelGestioneIO.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelGestioneIO.setObjectName("labelGestioneIO")
        self.gridLayout.addWidget(self.labelGestioneIO, 0, 0, 1, 1)
        self.layoutContainerHBox = QtWidgets.QHBoxLayout()
        self.layoutContainerHBox.setObjectName("layoutContainerHBox")
        self.gridLayout.addLayout(self.layoutContainerHBox, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 2, 1)

        self.retranslateUi(IOPage)
        QtCore.QMetaObject.connectSlotsByName(IOPage)

    def retranslateUi(self, IOPage):
        _translate = QtCore.QCoreApplication.translate
        self.labelGestioneIO.setText(_translate("IOPage", "GESTIONE I/O"))
        self.labelGestioneIO.setStyleSheet(_translate("IOPage", "font-weight: bold; font-size: 14pt;"))
