# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\LAVORO\PRODAR\CLAUDIA\CARRELLI\carrelli elettrici\PYTHON\CARRELLI_SMAO_SMIOO\widgets\container_widget\container.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContainerWidget(object):
    def setupUi(self, ContainerWidget):
        ContainerWidget.setObjectName("ContainerWidget")
        ContainerWidget.resize(94, 112)
        ContainerWidget.setStyleSheet("")
        self.gridLayout_2 = QtWidgets.QGridLayout(ContainerWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(ContainerWidget)
        self.frame.setStyleSheet("#frame{\n"
"border: 1px solid black;\n"
"border-radius: 4px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelType = QtWidgets.QLabel(self.frame)
        self.labelType.setAlignment(QtCore.Qt.AlignCenter)
        self.labelType.setObjectName("labelType")
        self.verticalLayout.addWidget(self.labelType)
        self.signalContainer = QtWidgets.QVBoxLayout()
        self.signalContainer.setObjectName("signalContainer")
        self.verticalLayout.addLayout(self.signalContainer)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(ContainerWidget)
        QtCore.QMetaObject.connectSlotsByName(ContainerWidget)

    def retranslateUi(self, ContainerWidget):
        _translate = QtCore.QCoreApplication.translate
        self.labelType.setStyleSheet(_translate("ContainerWidget", "font-weight:bold;font-size:10pt"))
        self.labelType.setText(_translate("ContainerWidget", "Tipo"))
