# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\LAVORO\PRODAR\CLAUDIA\CARRELLI\carrelli elettrici\PYTHON\CARRELLI_SMAO_SMIOO\widgets\cycle_page\cycle_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_CyclePage(object):
    def setupUi(self, CyclePage):
        CyclePage.setObjectName("CyclePage")
        self.gridLayoutMain = QtWidgets.QGridLayout(CyclePage)
        self.gridLayoutMain.setObjectName("gridLayoutMain")
        self.layoutCycles = QtWidgets.QVBoxLayout()
        self.layoutCycles.setObjectName("layoutCycles")
        self.labelCycles = QtWidgets.QLabel(CyclePage)
        self.labelCycles.setObjectName("labelCycles")
        self.layoutCycles.addWidget(self.labelCycles)
        self.listCycles = QtWidgets.QListWidget(CyclePage)
        self.listCycles.setObjectName("listCycles")
        self.layoutCycles.addWidget(self.listCycles)
        self.gridLayoutMain.addLayout(self.layoutCycles, 0, 0, 1, 1)
        self.pluginContainer = QtWidgets.QStackedWidget(CyclePage)
        self.pluginContainer.setObjectName("pluginContainer")
        self.gridLayoutMain.addWidget(self.pluginContainer, 0, 1, 1, 1)
        self.groupBoxCheckbox = QtWidgets.QGroupBox(CyclePage)
        self.groupBoxCheckbox.setObjectName("groupBoxCheckbox")
        self.layoutCheckbox = QtWidgets.QGridLayout(self.groupBoxCheckbox)
        self.layoutCheckbox.setObjectName("layoutCheckbox")
        self.gridLayoutMain.addWidget(self.groupBoxCheckbox, 1, 0, 1, 2)
        self.cycleChartView = QtChart.QChartView(CyclePage)
        self.cycleChartView.setObjectName("cycleChartView")
        self.gridLayoutMain.addWidget(self.cycleChartView, 2, 0, 1, 1)
        self.cycleDataTable = QtWidgets.QTableWidget(CyclePage)
        self.cycleDataTable.setObjectName("cycleDataTable")
        self.cycleDataTable.setColumnCount(0)
        self.cycleDataTable.setRowCount(0)
        self.gridLayoutMain.addWidget(self.cycleDataTable, 2, 1, 1, 1)

        self.retranslateUi(CyclePage)

    def retranslateUi(self, CyclePage):
        _translate = QtCore.QCoreApplication.translate
        CyclePage.setWindowTitle(_translate("CyclePage", "Cicli di Collaudo"))
        self.labelCycles.setText(_translate("CyclePage", "Cicli disponibili:"))
        self.groupBoxCheckbox.setTitle(_translate("CyclePage", "Visualizza Misure"))


from PyQt5 import QtChart
