# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\LAVORO\PRODAR\CLAUDIA\CARRELLI\carrelli elettrici\PYTHON\CARRELLI_SMAO_SMIOO\widgets\products_management_page\products_management_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProductsManagementPage(object):
    def setupUi(self, ProductsManagementPage):
        ProductsManagementPage.setObjectName("ProductsManagementPage")
        ProductsManagementPage.resize(1000, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProductsManagementPage)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelHeader = QtWidgets.QLabel(ProductsManagementPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.labelHeader.setFont(font)
        self.labelHeader.setStyleSheet("background-color: #34495E; color: white; padding: 10px;")
        self.labelHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeader.setObjectName("labelHeader")
        self.verticalLayout.addWidget(self.labelHeader)
        self.toolbarLayout = QtWidgets.QHBoxLayout()
        self.toolbarLayout.setSpacing(10)
        self.toolbarLayout.setObjectName("toolbarLayout")
        self.labelSearch = QtWidgets.QLabel(ProductsManagementPage)
        font = QtGui.QFont()
        font.setBold(True)
        self.labelSearch.setFont(font)
        self.labelSearch.setObjectName("labelSearch")
        self.toolbarLayout.addWidget(self.labelSearch)
        self.inputSearch = QtWidgets.QLineEdit(ProductsManagementPage)
        self.inputSearch.setMaximumSize(QtCore.QSize(300, 16777215))
        self.inputSearch.setObjectName("inputSearch")
        self.toolbarLayout.addWidget(self.inputSearch)
        self.labelFilterType = QtWidgets.QLabel(ProductsManagementPage)
        font = QtGui.QFont()
        font.setBold(True)
        self.labelFilterType.setFont(font)
        self.labelFilterType.setObjectName("labelFilterType")
        self.toolbarLayout.addWidget(self.labelFilterType)
        self.comboType = QtWidgets.QComboBox(ProductsManagementPage)
        self.comboType.setMinimumSize(QtCore.QSize(250, 0))
        self.comboType.setMaximumSize(QtCore.QSize(400, 16777215))
        self.comboType.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboType.setObjectName("comboType")
        self.comboType.addItem("")
        self.toolbarLayout.addWidget(self.comboType)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolbarLayout.addItem(spacerItem)
        self.btnNew = QtWidgets.QPushButton(ProductsManagementPage)
        self.btnNew.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnNew.setFont(font)
        self.btnNew.setStyleSheet("QPushButton {\n"
"    background-color: #27AE60;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2ECC71;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #229954;\n"
"}")
        self.btnNew.setObjectName("btnNew")
        self.toolbarLayout.addWidget(self.btnNew)
        self.btnEdit = QtWidgets.QPushButton(ProductsManagementPage)
        self.btnEdit.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEdit.setFont(font)
        self.btnEdit.setStyleSheet("QPushButton {\n"
"    background-color: #3498DB;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5DADE2;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2980B9;\n"
"}")
        self.btnEdit.setObjectName("btnEdit")
        self.toolbarLayout.addWidget(self.btnEdit)
        self.btnDelete = QtWidgets.QPushButton(ProductsManagementPage)
        self.btnDelete.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDelete.setFont(font)
        self.btnDelete.setStyleSheet("QPushButton {\n"
"    background-color: #E74C3C;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EC7063;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #C0392B;\n"
"}")
        self.btnDelete.setObjectName("btnDelete")
        self.toolbarLayout.addWidget(self.btnDelete)
        self.btnImportJSON = QtWidgets.QPushButton(ProductsManagementPage)
        self.btnImportJSON.setMinimumSize(QtCore.QSize(130, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnImportJSON.setFont(font)
        self.btnImportJSON.setStyleSheet("QPushButton {\n"
"    background-color: #9B59B6;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #BB8FCE;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #8E44AD;\n"
"}")
        self.btnImportJSON.setObjectName("btnImportJSON")
        self.toolbarLayout.addWidget(self.btnImportJSON)
        self.verticalLayout.addLayout(self.toolbarLayout)
        self.tableProducts = QtWidgets.QTableView(ProductsManagementPage)
        self.tableProducts.setAlternatingRowColors(True)
        self.tableProducts.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableProducts.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableProducts.setSortingEnabled(False)
        self.tableProducts.setObjectName("tableProducts")
        self.tableProducts.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableProducts)
        self.labelInfo = QtWidgets.QLabel(ProductsManagementPage)
        self.labelInfo.setStyleSheet("color: #7F8C8D; font-style: italic;")
        self.labelInfo.setObjectName("labelInfo")
        self.verticalLayout.addWidget(self.labelInfo)

        self.retranslateUi(ProductsManagementPage)
        QtCore.QMetaObject.connectSlotsByName(ProductsManagementPage)

    def retranslateUi(self, ProductsManagementPage):
        _translate = QtCore.QCoreApplication.translate
        ProductsManagementPage.setWindowTitle(_translate("ProductsManagementPage", "Gestione Database Prodotti"))
        self.labelHeader.setText(_translate("ProductsManagementPage", "🗄️ GESTIONE DATABASE PRODOTTI"))
        self.labelSearch.setText(_translate("ProductsManagementPage", "Cerca:"))
        self.inputSearch.setPlaceholderText(_translate("ProductsManagementPage", "Codice, Tipo o Descrizione..."))
        self.labelFilterType.setText(_translate("ProductsManagementPage", "Tipo:"))
        self.comboType.setItemText(0, _translate("ProductsManagementPage", "Tutti i tipi"))
        self.btnNew.setText(_translate("ProductsManagementPage", "➕ Nuovo"))
        self.btnEdit.setText(_translate("ProductsManagementPage", "✏️ Modifica"))
        self.btnDelete.setText(_translate("ProductsManagementPage", "🗑️ Elimina"))
        self.btnImportJSON.setText(_translate("ProductsManagementPage", "📥 Importa JSON"))
        self.labelInfo.setText(_translate("ProductsManagementPage", "Totale: 0 prodotti"))
