# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\LAVORO\PRODAR\CLAUDIA\CARRELLI\carrelli elettrici\PYTHON\CARRELLI_SMAO_SMIOO\widgets\io_widget\io_widget_generic.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IOWidgetGeneric(object):
    def setupUi(self, IOWidgetGeneric):
        IOWidgetGeneric.setObjectName("IOWidgetGeneric")
        IOWidgetGeneric.resize(600, 420)
        self.verticalLayout = QtWidgets.QVBoxLayout(IOWidgetGeneric)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelHeader = QtWidgets.QLabel(IOWidgetGeneric)
        self.labelHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeader.setObjectName("labelHeader")
        self.verticalLayout.addWidget(self.labelHeader)
        self.tableIO = QtWidgets.QTableWidget(IOWidgetGeneric)
        self.tableIO.setColumnCount(4)
        self.tableIO.setRowCount(16)
        self.tableIO.setObjectName("tableIO")
        item = QtWidgets.QTableWidgetItem()
        self.tableIO.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableIO.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableIO.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableIO.setHorizontalHeaderItem(3, item)
        self.tableIO.horizontalHeader().setDefaultSectionSize(120)
        self.verticalLayout.addWidget(self.tableIO)

        self.retranslateUi(IOWidgetGeneric)
        QtCore.QMetaObject.connectSlotsByName(IOWidgetGeneric)

    def retranslateUi(self, IOWidgetGeneric):
        _translate = QtCore.QCoreApplication.translate
        IOWidgetGeneric.setWindowTitle(_translate("IOWidgetGeneric", "I/O Digitali"))
        self.labelHeader.setText(_translate("IOWidgetGeneric", "Intestazione dinamica"))
        self.labelHeader.setStyleSheet(_translate("IOWidgetGeneric", "font-weight: bold; font-size: 14pt;"))
        item = self.tableIO.horizontalHeaderItem(0)
        item.setText(_translate("IOWidgetGeneric", "Nome"))
        item = self.tableIO.horizontalHeaderItem(1)
        item.setText(_translate("IOWidgetGeneric", "Stato"))
        item = self.tableIO.horizontalHeaderItem(2)
        item.setText(_translate("IOWidgetGeneric", "Toggle"))
        item = self.tableIO.horizontalHeaderItem(3)
        item.setText(_translate("IOWidgetGeneric", "Note"))
