# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\LAVORO\PRODAR\CLAUDIA\CARRELLI\carrelli elettrici\PYTHON\CARRELLI_SMAO_SMIOO\widgets\led_indicator\led_indicator_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_LedIndicatorWidget(object):
    def setupUi(self, LedIndicatorWidget):
        LedIndicatorWidget.setObjectName("LedIndicatorWidget")
        LedIndicatorWidget.setMinimumSize(QtCore.QSize(24, 24))
        LedIndicatorWidget.setMaximumSize(QtCore.QSize(48, 48))
        LedIndicatorWidget.setStyleSheet("background: transparent;")
        self.verticalLayout = QtWidgets.QVBoxLayout(LedIndicatorWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelLed = QtWidgets.QLabel(LedIndicatorWidget)
        self.labelLed.setMinimumSize(QtCore.QSize(16, 16))
        self.labelLed.setMaximumSize(QtCore.QSize(32, 32))
        self.labelLed.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLed.setStyleSheet(
            "\n"
            "        border-radius: 12px;\n"
            "        background: #cccccc;\n"
            "                        "
        )
        self.labelLed.setText("")
        self.labelLed.setObjectName("labelLed")
        self.verticalLayout.addWidget(self.labelLed)

        self.retranslateUi(LedIndicatorWidget)
        QtCore.QMetaObject.connectSlotsByName(LedIndicatorWidget)

    def retranslateUi(self, LedIndicatorWidget):
        pass
