# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\LAVORO\PRODAR\CLAUDIA\CARRELLI\carrelli elettrici\PYTHON\CARRELLI_SMAO_SMIOO\cycle_plugins\CicloRipetibilità\CicloRipetibilita.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CicloRipetibilitaForm(object):
    def setupUi(self, CicloRipetibilitaForm):
        CicloRipetibilitaForm.setObjectName("CicloRipetibilitaForm")
        CicloRipetibilitaForm.resize(328, 289)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CicloRipetibilitaForm.sizePolicy().hasHeightForWidth())
        CicloRipetibilitaForm.setSizePolicy(sizePolicy)
        CicloRipetibilitaForm.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(CicloRipetibilitaForm)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.labelTitle = QtWidgets.QLabel(CicloRipetibilitaForm)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.spinRipetizioni = QtWidgets.QSpinBox(CicloRipetibilitaForm)
        self.spinRipetizioni.setMinimum(1)
        self.spinRipetizioni.setMaximum(10000)
        self.spinRipetizioni.setProperty("value", 10)
        self.spinRipetizioni.setObjectName("spinRipetizioni")
        self.verticalLayout.addWidget(self.spinRipetizioni)
        self.btnStart = QtWidgets.QPushButton(CicloRipetibilitaForm)
        self.btnStart.setObjectName("btnStart")
        self.verticalLayout.addWidget(self.btnStart)
        self.progressBar = QtWidgets.QProgressBar(CicloRipetibilitaForm)
        self.progressBar.setStyleSheet("")
        self.progressBar.setMaximum(10)
        self.progressBar.setProperty("value", 5)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.btnStop = QtWidgets.QPushButton(CicloRipetibilitaForm)
        self.btnStop.setObjectName("btnStop")
        self.verticalLayout.addWidget(self.btnStop)
        self.labelStatus = QtWidgets.QLabel(CicloRipetibilitaForm)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)

        self.retranslateUi(CicloRipetibilitaForm)
        QtCore.QMetaObject.connectSlotsByName(CicloRipetibilitaForm)

    def retranslateUi(self, CicloRipetibilitaForm):
        _translate = QtCore.QCoreApplication.translate
        CicloRipetibilitaForm.setWindowTitle(_translate("CicloRipetibilitaForm", "Ripetibilità - Parametri"))
        self.labelTitle.setText(_translate("CicloRipetibilitaForm", "Ciclo di ripetibilità"))
        self.btnStart.setText(_translate("CicloRipetibilitaForm", "START"))
        self.btnStop.setText(_translate("CicloRipetibilitaForm", "STOP"))
