# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\LAVORO\PRODAR\CLAUDIA\CARRELLI\carrelli elettrici\PYTHON\CARRELLI_SMAO_SMIOO\widgets\plot_page\plot_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotPage(object):
    def setupUi(self, PlotPage):
        PlotPage.setObjectName("PlotPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(PlotPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(PlotPage)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.listFiles = QtWidgets.QListWidget(PlotPage)
        self.listFiles.setObjectName("listFiles")
        self.verticalLayout.addWidget(self.listFiles)
        self.btnPlot = QtWidgets.QPushButton(PlotPage)
        self.btnPlot.setObjectName("btnPlot")
        self.verticalLayout.addWidget(self.btnPlot)
        self.chartFrame = QtWidgets.QWidget(PlotPage)
        self.chartFrame.setMinimumSize(QtCore.QSize(600, 300))
        self.chartFrame.setObjectName("chartFrame")
        self.verticalLayout.addWidget(self.chartFrame)

        self.retranslateUi(PlotPage)
        QtCore.QMetaObject.connectSlotsByName(PlotPage)

    def retranslateUi(self, PlotPage):
        _translate = QtCore.QCoreApplication.translate
        PlotPage.setWindowTitle(_translate("PlotPage", "Grafico Collaudo"))
        self.labelTitle.setText(_translate("PlotPage", "File di Collaudo"))
        self.btnPlot.setText(_translate("PlotPage", "Visualizza Grafico"))
