# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\LAVORO\PRODAR\CLAUDIA\CARRELLI\carrelli elettrici\PYTHON\CARRELLI_SMAO_SMIOO\widgets\measurement_indicator\measurement_indicator_test_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(913, 95)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.displacementIndicator = DisplacementIndicator(Form)
        self.displacementIndicator.setProperty("value", 25.0)
        self.displacementIndicator.setProperty("minRange", -100.0)
        self.displacementIndicator.setProperty("maxRange", 100.0)
        self.displacementIndicator.setProperty("minLimit", -80.0)
        self.displacementIndicator.setProperty("maxLimit", 80.0)
        self.displacementIndicator.setProperty("decimals", 2)
        self.displacementIndicator.setProperty("barHeightRatio", 0.5)
        self.displacementIndicator.setProperty("barMargin", 30)
        self.displacementIndicator.setProperty("widgetHeight", 45)
        self.displacementIndicator.setObjectName("displacementIndicator")
        self.verticalLayout.addWidget(self.displacementIndicator)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.displacementIndicator.setProperty("label", _translate("Form", "T-01"))
        self.displacementIndicator.setProperty("unit", _translate("Form", "µm"))
        self.label.setText(_translate("Form", "CODICE"))
        self.label_2.setText(_translate("Form", "MATRICOLA"))
        self.label_3.setText(_translate("Form", "DESCRIZIONE"))
from displacement_indicator import DisplacementIndicator
